name: Setup KernelSU
description: 使用官方脚本集成最新的 KernelSU 源码

inputs:
  ksu_commit:
    description: "KSU 分支、标签或提交哈希 (默认: main)"
    required: false
    default: "main"

runs:
  using: composite
  steps:
    - name: Run Official KernelSU Setup
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        KSU_TARGET="${{ inputs.ksu_commit }}"
        if [ -z "$KSU_TARGET" ]; then
            KSU_TARGET="main"
        fi
        echo "正在安装官方 KernelSU，目标: $KSU_TARGET"
        # 官方脚本会自动克隆 KernelSU 到 common/KernelSU 并建立 drivers/kernelsu 链接
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s "$KSU_TARGET"

    - name: Extract KSU Version Info
      id: ksu-version
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common/KernelSU
      run: |
        KSU_GIT_VERSION=$(git rev-list --count HEAD 2>/dev/null)
        KSU_GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
        KSU_COMMIT=$(git rev-parse --short HEAD 2>/dev/null)
        KSU_VERSION=$((30000 + KSU_GIT_VERSION))
        
        echo "KSU_GIT_TAG=$KSU_GIT_TAG" >> $GITHUB_ENV
        echo "KSU_VERSION=$KSU_VERSION" >> $GITHUB_ENV
        echo "KSU_COMMIT=$KSU_COMMIT" >> $GITHUB_ENV
