name: Setup SUSFS
description: Clone and apply SUSFS patches with version-specific fixes
inputs:
  android_version:
    description: 'Android version (e.g., android15)'
    required: true
  kernel_version:
    description: 'Kernel version (e.g., 6.6)'
    required: true
  os_patch_level:
    description: 'OS patch level (e.g., 2024-07)'
    required: true
  sublevel:
    description: 'Kernel sublevel'
    required: true

runs:
  using: composite
  steps:
    - name: Setup SUSFS Branch
      shell: bash
      run: |
        SUSFS_BRANCH="gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}"
        if [ -d "susfs_cache/$SUSFS_BRANCH" ]; then
          rm -rf susfs4ksu
          cp -r "susfs_cache/$SUSFS_BRANCH" susfs4ksu
        else
          echo "ERROR: SUSFS branch $SUSFS_BRANCH not found in downloaded artifacts"
          exit 1
        fi
        SUSFS_VERSION="2.0.0"
        echo "SUSFS_VERSION=$SUSFS_VERSION" >> $GITHUB_ENV

    - name: Apply SUSFS Patches
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        # 1. 复制头文件和 fs 实现 (复现命令 16577, 16578)
        cp -r "${{ github.workspace }}/susfs4ksu/kernel_patches/include/linux/"* include/linux/
        cp -r "${{ github.workspace }}/susfs4ksu/kernel_patches/fs/"* fs/

        # 2. 应用针对 KernelSU 的补丁 (复现命令 16576, 16579, 16580)
        if [ -d "KernelSU" ]; then
            cp "${{ github.workspace }}/susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch" KernelSU/
            cd KernelSU
            patch -p1 < 10_enable_susfs_for_ksu.patch
            cd ..
        fi

        # 3. 应用 GKI 主补丁 (复现命令 16582)
        cp "${{ github.workspace }}/susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch" ./
        patch -p1 < "50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch"

    - name: Enable Configurations via Kconfig
      # 复现命令 16583
      # 必须在补丁打完后运行，才能捕获到补丁新增加的 KSU_SUSFS 选项
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        if [ -f "drivers/kernelsu/Kconfig" ]; then
            sed -i 's/default n/default y/' drivers/kernelsu/Kconfig
            echo "Kconfig modified to enable KernelSU and SUSFS by default."
        else
            echo "Error: drivers/kernelsu/Kconfig not found!"
            exit 1
        fi

    - name: Commit Changes
      # 复现命令 16584
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        git config --global user.email "bot@github.com"
        git config --global user.name "GitHub Bot"
        if [ -d "KernelSU" ]; then
            cd KernelSU
            git add -A
            git commit -m "Add SUSFS to KernelSU" || true
            cd ..
        fi
        git add -A
        git commit -m "Add SUSFS to Kernel" || true